In [14]:
#note some data merging and cleaning code has been deleted to avoid conflicts.
#much of the datae exchanges between team members was done using either github or slack. slack exchanges can be provided if needed
import pandas as pd
import numpy as np
from uszipcode import SearchEngine

In [15]:
underlying_cause = "underlying_cause_final.csv"
#read in and sorted original obgyn data earlier with code below, matching it to zip code and county. don't know why I deleted read in code afterwards

In [16]:
underlying_cause_df = pd.read_csv(underlying_cause
                                  , encoding="ISO-8859-1")

In [26]:
obgyn_by_county_df.head()

   County Name  Providers Count
0        ADAMS                5
1        ALLEN              182
2  BARTHOLOMEW               13
3        BOONE                8
4         CASS                6

In [27]:
obgyn_by_county_df.describe()

       Providers Count
count        68.000000
mean         28.750000
std          74.668496
min           1.000000
25%           4.000000
50%           9.000000
75%          22.000000
max         571.000000

In [28]:
underlying_cause_df.head()

,CNTY,CHILD_DEATH_YR,UNDERLYING_COD,CNT_BY_UNDERLYING_COD,CNTY_YR_DEATH_TOTAL,PCT_CNTY_YR_TOTAL,CHILD_DEATH_CNTY_POP,CNTY_YR_DEATH_TOTAL_PER_10000_CNTY_RES
0,ADAMS,2010,Other specified noninfective disorders of lymp...,1,4,25.0,34387,1.16
1,ADAMS,2010,Unspecified pulmonary hemorrhage originating i...,1,4,25.0,34387,1.16
2,ADAMS,2010,"Congenital malformation of the heart, unspecified",1,4,25.0,34387,1.16
3,ADAMS,2010,"Polycystic kidney, unspecified",1,4,25.0,34387,1.16
4,ADAMS,2011,Primary atelectasis of newborn,1,5,20.0,34384,1.45

In [17]:
underlying_cause_df.describe()

,CHILD_DEATH_YR,CNT_BY_UNDERLYING_COD,CNTY_YR_DEATH_TOTAL,PCT_CNTY_YR_TOTAL,CHILD_DEATH_CNTY_POP,CNTY_YR_DEATH_TOTAL_PER_10000_CNTY_RES
count,2393.000000,2393.000000,2393.000000,2393.000000,2393.000000,2393.000000
mean,2014.029252,1.193481,16.910990,24.713725,272709.632679,0.661463
std,2.531239,0.717501,21.224887,26.714584,308761.865396,0.340800
min,2010.000000,1.000000,1.000000,1.388800,8166.000000,0.050000
25%,2012.000000,1.000000,3.000000,6.250000,44013.000000,0.440000
50%,2014.000000,1.000000,7.000000,16.666600,143535.000000,0.620000
75%,2016.000000,1.000000,19.000000,33.333300,363265.000000,0.770000
max,2018.000000,11.000000,72.000000,100.000000,941229.000000,3.150000

In [47]:
#data cleaning starts here. started with a much larger file for indiana obgyns sorted file but was causing problems on reruns so removed lines of code relevant to that process

IndianaData = "Indiana_OBGYNS_Final.csv"
IndianaDF = pd.read_csv(IndianaData)
IndianaDF

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,NPI,PAC ID,Professional Enrollment ID,Last Name,First Name,Middle Name,Gender,...,Line 1 Street Address,Line 2 Street Address,City,State,Zip,Zip Code,Phone Number,County,Lat,Long
0,0,0,0,1003082215,5991975641,I20170714000622,THOTA,SHARMILEE,NaN,F,...,1704 LAFAYETTE RD,NaN,CRAWFORDSVILLE,IN,47933,479331071,NaN,Montgomery,40.00,-86.90
1,1,1,1,1003811217,4880611532,I20100816000979,SILVA,GUY,DUNCAN,M,...,1919 STATE ST,SUITE 340,NEW ALBANY,IN,47150,471506807,8.129460e+12,Floyd,38.30,-85.80
2,2,2,2,1003880527,7113823758,I20100629000881,SINGH,GITA,NaN,F,...,2512 E DUPONT RD,SUITE 100,FORT WAYNE,IN,46825,468251609,2.604367e+09,Allen,41.15,-85.11
3,3,3,3,1013052794,345364709,I20100908000240,LEACHMAN HAAB,BRIANNA,NaN,F,...,2600 GREENBUSH ST,NaN,LAFAYETTE,IN,47904,479042477,7.654488e+09,Tippecanoe,40.44,-86.88
4,4,4,4,1013262195,547555203,I20160822000042,SIDES,CHARLES,C,M,...,221 S 6 TH ST,APANDS CLINIC DOWNTOWN,TERRE HAUTE,IN,47807,478074214,8.122321e+09,Vigo,39.47,-87.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
748,748,748,748,1902857147,4284612425,I20050707000089,FRENCH,ADAM,A A,M,...,4005 NORTHSIDE DR,NaN,NEW ALBANY,IN,47150,471508306,8.129448e+09,Floyd,38.30,-85.80
749,749,749,749,1952304123,8022927631,I20100429000737,CONWELL,CARL,NaN,M,...,2229 MARY SHERMAN DR,NaN,SULLIVAN,IN,47882,478827633,8.122683e+09,Sullivan,39.10,-87.40
750,750,750,750,1952662777,1557500501,I20151119002602,LASATER,MALINDA,J,F,...,2824 ELKHART RD,NaN,GOSHEN,IN,46526,465261014,5.745352e+09,Elkhart,41.60,-85.90
751,751,751,751,1962460964,9537176755,I20100303000903,MERNITZ,ANDREA,NaN,F,...,3203 MIDDLE DR,NaN,COLUMBUS,IN,47203,472034427,8.123733e+09,Bartholomew,39.20,-85.80
752,752,752,752,1962658989,3779630926,I20090406000246,ELLIS,DUSTIN,C,M,...,2186 N HOSPITAL BLVD,2 LAKESIDE FAMILY MEDICAL,SULLIVAN,IN,47882,478827654,8.122683e+09,Sullivan,39.10,-87.40

In [21]:
#use of uszipcode starts here some modifications made to keep from reovewriting modified data
search = SearchEngine(simple_zipcode=False)

In [31]:
Lat = []
Long = []
county = []
ZipCodes = IndianaDF["Zip"]
for littleZips in ZipCodes:
    zipcoding = search.by_zipcode(littleZips)
    ZipVar = zipcoding.to_dict()
    Lat.append(ZipVar["lat"])
    Long.append(ZipVar["lng"])
    county.append(ZipVar["county"])
Lat

[40.0,
 38.3,
 41.15,
 40.44,
 39.47,
 39.68,
 39.6,
 40.5,
 41.67,
 38.2,
 41.72,
 39.9,
 37.95,
 41.67,
 41.55,
 39.5,
 39.79,
 39.9,
 40.4,
 40.5,
 39.79,
 41.52,
 39.79,
 41.15,
 39.9,
 40.8,
 39.84,
 39.79,
 41.67,
 39.6,
 38.8,
 39.9,
 39.47,
 39.9,
 41.15,
 39.5,
 39.68,
 39.9,
 39.5,
 39.9,
 39.68,
 39.9,
 39.1,
 41.21,
 41.62,
 39.79,
 39.9,
 39.76,
 37.95,
 39.8,
 41.67,
 39.79,
 39.5,
 37.95,
 41.48,
 41.6,
 39.8,
 37.95,
 40.4,
 41.21,
 37.95,
 39.9,
 39.79,
 39.68,
 39.9,
 39.8,
 41.5,
 40.5,
 39.1,
 41.59,
 41.21,
 41.58,
 39.79,
 41.67,
 41.72,
 40.3,
 39.85,
 39.79,
 40.7,
 40.1,
 40.7,
 39.8,
 39.97,
 39.76,
 39.79,
 41.21,
 39.9,
 41.65,
 41.5,
 39.68,
 37.95,
 37.95,
 39.3,
 39.1,
 39.79,
 37.95,
 39.68,
 41.72,
 37.95,
 41.67,
 41.67,
 39.1,
 37.95,
 39.79,
 41.67,
 41.46,
 40.1,
 40.2,
 None,
 38.33,
 39.6,
 40.1,
 40.4,
 39.1,
 39.4,
 41.59,
 39.8,
 39.76,
 41.55,
 41.73,
 41.67,
 41.6,
 41.5,
 40.6,
 39.9,
 40.5,
 40.3,
 39.9,
 39.68,
 38.3,
 38.4,
 39.47,
 39.1,
 39.79,
 39.9,
 41.21,
 41.59,
 41.21,
 41.67,
 37.95,
 38.33,
 41.67,
 38.7,
 38.7,
 38.7,
 39.1,
 41.45,
 39.9,
 40.44,
 41.21,
 37.95,
 39.97,
 40.23,
 39.9,
 41.21,
 39.6,
 39.9,
 40.7,
 39.76,
 37.95,
 39.79,
 40.8,
 38.6,
 41.45,
 38.4,
 39.0,
 39.9,
 39.97,
 41.55,
 41.15,
 39.2,
 40.4,
 41.21,
 37.95,
 39.9,
 39.9,
 41.61,
 38.6,
 41.21,
 38.3,
 39.9,
 41.21,
 39.2,
 40.1,
 40.44,
 39.9,
 41.15,
 41.67,
 39.79,
 39.3,
 39.9,
 41.15,
 41.72,
 40.4,
 39.9,
 39.76,
 41.55,
 39.0,
 40.4,
 None,
 41.73,
 41.0,
 39.6,
 41.66,
 39.8,
 39.3,
 39.97,
 39.76,
 39.68,
 39.9,
 39.79,
 38.9,
 39.76,
 39.9,
 41.21,
 38.8,
 41.67,
 40.4,
 41.21,
 41.67,
 39.9,
 39.0,
 39.79,
 39.9,
 41.15,
 39.79,
 39.9,
 41.65,
 41.21,
 40.5,
 39.76,
 39.79,
 39.68,
 41.67,
 39.5,
 38.6,
 39.9,
 39.76,
 39.9,
 40.8,
 40.4,
 39.2,
 41.6,
 39.79,
 41.1,
 37.95,
 39.9,
 37.95,
 39.79,
 40.0,
 41.55,
 41.7,
 37.95,
 39.5,
 41.69,
 38.3,
 40.23,
 38.33,
 40.7,
 39.1,
 41.67,
 39.8,
 39.79,
 41.55,
 41.15,
 39.9,
 39.9,
 39.76,
 38.3,
 41.69,
 39.79,
 39.56,
 39.79,
 38.3,
 39.9,
 41.21,
 40.1,
 39.9,
 39.9,
 37.95,
 39.76,
 40.1,
 40.4,
 39.9,
 39.9,
 38.4,
 41.72,
 39.4,
 39.9,
 38.9,
 41.69,
 41.55,
 37.95,
 39.4,
 41.6,
 41.49,
 40.4,
 40.2,
 39.9,
 40.23,
 39.9,
 37.95,
 38.33,
 37.95,
 39.97,
 41.21,
 41.21,
 39.79,
 39.9,
 41.1,
 39.68,
 39.8,
 39.79,
 41.69,
 39.9,
 37.95,
 39.9,
 40.06,
 39.5,
 39.76,
 41.69,
 39.97,
 41.15,
 41.6,
 41.72,
 39.9,
 41.66,
 37.95,
 39.97,
 39.76,
 39.9,
 39.9,
 41.55,
 39.9,
 39.79,
 41.48,
 39.8,
 41.55,
 40.23,
 41.48,
 39.97,
 41.6,
 40.0,
 39.2,
 40.1,
 39.9,
 39.79,
 37.95,
 39.9,
 39.9,
 40.1,
 41.5,
 39.9,
 41.72,
 39.5,
 41.6,
 39.9,
 41.21,
 40.0,
 41.21,
 39.78,
 38.31,
 39.47,
 38.4,
 39.79,
 38.8,
 38.8,
 40.1,
 39.4,
 39.5,
 39.68,
 39.9,
 39.47,
 39.8,
 37.95,
 39.68,
 39.9,
 39.9,
 39.1,
 41.67,
 41.21,
 39.0,
 39.0,
 41.3,
 39.9,
 41.21,
 39.9,
 39.9,
 41.61,
 38.33,
 39.9,
 41.15,
 39.79,
 39.76,
 39.78,
 41.67,
 39.5,
 38.2,
 39.2,
 39.9,
 41.21,
 41.21,
 39.79,
 41.69,
 39.9,
 37.95,
 39.9,
 39.9,
 38.9,
 39.9,
 41.45,
 40.9,
 39.2,
 41.67,
 39.9,
 38.6,
 39.9,
 37.95,
 39.6,
 39.9,
 39.83,
 39.97,
 39.2,
 40.5,
 41.58,
 39.47,
 39.68,
 41.46,
 40.0,
 39.79,
 41.67,
 39.76,
 38.33,
 39.81,
 39.79,
 39.9,
 37.95,
 38.31,
 40.0,
 37.95,
 37.95,
 41.67,
 41.5,
 41.69,
 39.79,
 41.21,
 41.49,
 39.6,
 39.9,
 41.55,
 41.4,
 41.21,
 41.48,
 41.67,
 38.4,
 39.9,
 37.95,
 39.76,
 41.21,
 39.9,
 41.48,
 41.2,
 39.0,
 40.1,
 37.95,
 41.45,
 38.3,
 41.21,
 41.21,
 39.79,
 41.6,
 37.95,
 41.45,
 41.21,
 40.23,
 41.7,
 38.2,
 40.4,
 41.59,
 37.95,
 39.3,
 40.1,
 41.72,
 41.48,
 39.3,
 41.5,
 41.45,
 40.0,
 39.78,
 39.79,
 41.4,
 39.85,
 40.0,
 41.21,
 41.55,
 39.9,
 41.6,
 41.2,
 39.79,
 39.68,
 37.95,
 37.95,
 39.6,
 40.44,
 40.1,
 39.1,
 39.97,
 41.21,
 40.1,
 40.23,
 40.0,
 39.9,
 38.9,
 41.6,
 39.6,
 39.9,
 39.79,
 41.5,
 39.8,
 39.9,
 39.68,
 39.76,
 39.97,
 39.78,
 39.2,
 39.62,
 39.79,
 37.95,
 39.9,
 39.1,
 41.65,
 39.97,
 41.21,
 40.23,
 39.1,
 39.97,
 39.1,
 41.5,
 41.15,
 41.21,
 41.49,
 40.5,
 41.55,
 37.95,
 39.6,
 39.9,
 38.7,
 39.97,
 39.1,
 39.9,
 41.6,
 39.9,
 41.48,
 39.0,
 41.49,
 39.8,
 41.05,
 37.95,
 37.95,
 39.9,
 39.1,
 39.9,
 39.9,
 39.9,
 41.21,
 41.21,
 41.45,
 39.79,
 41.67,
 40.23,
 40.1,
 38.6,
 39.1,
 39.79,
 41.4,
 39.8,
 40.1,
 40.0,
 39.79,
 40.0,
 40.0,
 41.4,
 39.79,
 41.21,
 41.5,
 40.44,
 39.85,
 39.79,
 41.4,
 41.69,
 39.9,
 41.67,
 39.79,
 41.4,
 39.99,
 39.85,
 41.45,
 37.95,
 39.79,
 40.5,
 38.3,
 39.2,
 39.9,
 39.78,
 40.0,
 40.4,
 41.67,
 39.9,
 39.97,
 40.8,
 41.15,
 38.33,
 41.55,
 37.95,
 39.9,
 40.1,
 41.15,
 41.4,
 41.6,
 40.44,
 41.7,
 41.6,
 41.4,
 39.68,
 41.4,
 41.15,
 41.3,
 39.6,
 39.9,
 39.68,
 39.0,
 41.45,
 39.78,
 39.79,
 40.7,
 39.79,
 39.79,
 39.79,
 39.9,
 39.76,
 38.31,
 41.21,
 39.79,
 41.6,
 38.0,
 41.4,
 40.23,
 41.59,
 41.21,
 39.85,
 41.48,
 39.84,
 38.33,
 39.9,
 39.5,
 40.1,
 39.9,
 41.21,
 39.8,
 39.9,
 38.9,
 39.76,
 38.9,
 39.74,
 37.95,
 41.59,
 39.6,
 39.9,
 40.44,
 38.33,
 41.21,
 39.1,
 40.4,
 39.2,
 40.2,
 39.5,
 39.79,
 39.97,
 41.45,
 39.9,
 40.0,
 41.49,
 41.21,
 41.48,
 40.4,
 41.72,
 39.76,
 37.95,
 39.79,
 41.2,
 40.4,
 39.1,
 39.47,
 39.9,
 38.4,
 39.4,
 39.79,
 41.67,
 40.8,
 37.97,
 41.59,
 39.9,
 39.79,
 40.8,
 40.3,
 38.7,
 41.0,
 41.46,
 40.2,
 41.6,
 41.69,
 41.4,
 41.21,
 39.68,
 39.6,
 41.67,
 39.94,
 41.4,
 37.95,
 39.8,
 37.95,
 41.6,
 41.5,
 41.61,
 40.7,
 39.8,
 40.0,
 40.3,
 41.49,
 39.78,
 40.3,
 41.6,
 39.96,
 41.6,
 41.1,
 38.6,
 39.0,
 41.69,
 39.6,
 39.6,
 39.9,
 40.19,
 39.5,
 39.2,
 41.6,
 41.67,
 41.72,
 39.79,
 38.3,
 39.1,
 41.6,
 39.2,
 39.1]

In [50]:
#test run with zipcode module
zipcode = search.by_zipcode("82925")
zipcode.to_dict()

{'zipcode_type': 'Standard',
 'major_city': 'Cora',
 'post_office_city': 'Cora, WY',
 'common_city_list': ['Cora'],
 'county': 'Sublette County',
 'state': 'WY',
 'lat': 43.1,
 'lng': -109.9,
 'timezone': 'Mountain',
 'radius_in_miles': 31.0,
 'area_code_list': ['307'],
 'population': 304,
 'population_density': 0.0,
 'land_area_in_sqmi': 699.3,
 'water_area_in_sqmi': 13.25,
 'housing_units': 336,
 'occupied_housing_units': 144,
 'median_home_value': 491700,
 'median_household_income': 75400,
 'bounds_west': -110.235444,
 'bounds_east': -109.548706,
 'bounds_north': 43.547631,
 'bounds_south': 42.904212,
 'zipcode': '82925',
 'polygon': [[[-110.0293, 42.9823],
   [-110.02988, 42.9822],
   [-110.03068, 42.98205],
   [-110.0314, 42.98192],
   [-110.03239, 42.98189],
   [-110.03405, 42.98189],
   [-110.03626, 42.9819],
   [-110.03771, 42.9819],
   [-110.03929, 42.98189],
   [-110.04141, 42.98189],
   [-110.04245, 42.9819],
   [-110.04244, 42.98305],
   [-110.04244, 42.9838],
   [-110.04246, 42.98458],
   [-110.04244, 42.98502],
   [-110.04246, 42.98546],
   [-110.04244, 42.98676],
   [-110.04246, 42.98908],
   [-110.04246, 42.98966],
   [-110.04246, 42.99036],
   [-110.04245, 42.99111],
   [-110.04245, 42.99364],
   [-110.042441, 42.994361],
   [-110.041772, 42.99447],
   [-110.039813, 42.993858],
   [-110.039161, 42.993654],
   [-110.032003, 42.991399],
   [-110.0294, 42.99058],
   [-110.029085, 42.990459],
   [-110.02906, 42.99045],
   [-110.02878, 42.99036],
   [-110.02833, 42.99028],
   [-110.02768, 42.99001],
   [-110.02695, 42.98954],
   [-110.02606, 42.98885],
   [-110.02539, 42.98836],
   [-110.02479, 42.9878],
   [-110.02386, 42.98681],
   [-110.02296, 42.98573],
   [-110.02242, 42.98516],
   [-110.02176, 42.98459],
   [-110.02139, 42.98433],
   [-110.02097, 42.98415],
   [-110.019934, 42.983821],
   [-110.019851, 42.983729],
   [-110.019804, 42.983677],
   [-110.019306, 42.982205],
   [-110.017813, 42.97779],
   [-110.017316, 42.976319],
   [-110.01715, 42.975884],
   [-110.017017, 42.975536],
   [-110.016718, 42.974752],
   [-110.016653, 42.974582],
   [-110.016487, 42.974148],
   [-110.016107, 42.973969],
   [-110.015188, 42.973639],
   [-110.014403, 42.973243],
   [-110.014156, 42.973147],
   [-110.0132, 42.972776],
   [-110.013114, 42.97257],
   [-110.012767, 42.971733],
   [-110.012036, 42.970953],
   [-110.011804, 42.970542],
   [-110.01158, 42.969844],
   [-110.011484, 42.968527],
   [-110.011291, 42.967923],
   [-110.010933, 42.967127],
   [-110.010507, 42.966627],
   [-110.010029, 42.966237],
   [-110.009917, 42.965935],
   [-110.009843, 42.965397],
   [-110.009731, 42.965002],
   [-110.009612, 42.964782],
   [-110.009433, 42.96453],
   [-110.008283, 42.963415],
   [-110.007805, 42.962978],
   [-110.007663, 42.962849],
   [-110.007304, 42.962437],
   [-110.006498, 42.96174],
   [-110.006042, 42.961218],
   [-110.005273, 42.960493],
   [-110.005139, 42.960301],
   [-110.005179, 42.960181],
   [-110.005301, 42.959825],
   [-110.005342, 42.959706],
   [-110.005192, 42.959692],
   [-110.004554, 42.959388],
   [-110.00452, 42.95945],
   [-110.00433, 42.95989],
   [-110.00426, 42.96004],
   [-110.00419, 42.96012],
   [-110.00404, 42.96017],
   [-110.00369, 42.96018],
   [-110.00296, 42.96019],
   [-110.00221, 42.96021],
   [-110.00158, 42.96021],
   [-110.0015, 42.96023],
   [-110.00073, 42.96025],
   [-109.99935, 42.96027],
   [-109.99851, 42.9603],
   [-109.9979, 42.96031],
   [-109.99751, 42.96031],
   [-109.99657, 42.96033],
   [-109.99567, 42.96033],
   [-109.995566, 42.960332],
   [-109.9949, 42.96035],
   [-109.99416, 42.96036],
   [-109.99387, 42.960368],
   [-109.993245, 42.960388],
   [-109.99319, 42.96039],
   [-109.992556, 42.960396],
   [-109.991553, 42.960407],
   [-109.99121, 42.96041],
   [-109.99106, 42.960412],
   [-109.990315, 42.960425],
   [-109.989582, 42.960438],
   [-109.9895, 42.96044],
   [-109.98909, 42.96044],
   [-109.98909, 42.96209],
   [-109.989092, 42.96244],
   [-109.98911, 42.96444],
   [-109.98906, 42.96632],
   [-109.98906, 42.968439],
   [-109.98906, 42.96853],
   [-109.98908, 42.97044],
   [-109.98861, 42.97043],
   [-109.988508, 42.970422],
   [-109.98835, 42.97041],
   [-109.98688, 42.97007],
   [-109.986833, 42.97006],
   [-109.986274, 42.969942],
   [-109.986168, 42.969919],
   [-109.985852, 42.969853],
   [-109.985747, 42.969831],
   [-109.98525, 42.969725],
   [-109.98494, 42.96966],
   [-109.98429, 42.96953],
   [-109.98387, 42.96944],
   [-109.983765, 42.969393],
   [-109.98362, 42.96933],
   [-109.98345, 42.96923],
   [-109.983352, 42.969114],
   [-109.98334, 42.9691],
   [-109.983305, 42.968979],
   [-109.9833, 42.96896],
   [-109.98326, 42.96877],
   [-109.98321, 42.96861],
   [-109.983181, 42.968568],
   [-109.9831, 42.96845],
   [-109.98285, 42.96845],
   [-109.98264, 42.96852],
   [-109.98252, 42.96867],
   [-109.98249, 42.96884],
   [-109.98249, 42.968973],
   [-109.98249, 42.96912],
   [-109.98254, 42.96952],
   [-109.98257, 42.96997],
   [-109.98263, 42.97037],
   [-109.98264, 42.97073],
   [-109.982495, 42.971864],
   [-109.98249, 42.97191],
   [-109.98249, 42.97235],
   [-109.98246, 42.97249],
   [-109.98232, 42.9728],
   [-109.982297, 42.972786],
   [-109.982122, 42.972667],
   [-109.982007, 42.972549],
   [-109.981946, 42.972511],
   [-109.981831, 42.972465],
   [-109.981626, 42.9724],
   [-109.981404, 42.972343],
   [-109.981221, 42.972286],
   [-109.981168, 42.972244],
   [-109.981091, 42.972129],
   [-109.981038, 42.972011],
   [-109.981007, 42.971961],
   [-109.980977, 42.971935],
   [-109.980848, 42.971885],
   [-109.980656, 42.971862],
   [-109.980592, 42.971851],
   [-109.980497, 42.971835],
   [-109.980367, 42.971798],
   [-109.980298, 42.971763],
   [-109.980191, 42.971676],
   [-109.980001, 42.971462],
   [-109.979856, 42.971244],
   [-109.979627, 42.97097],
   [-109.979543, 42.970848],
   [-109.979512, 42.970763],
   [-109.979604, 42.970672],
   [-109.97967, 42.970588],
   [-109.97971, 42.970538],
   [-109.979772, 42.970432],
   [-109.979794, 42.970375],
   [-109.979802, 42.970294],
   [-109.979794, 42.970222],
   [-109.979733, 42.970131],
   [-109.979611, 42.969985],
   [-109.979565, 42.969906],
   [-109.979558, 42.969859],
   [-109.979581, 42.969619],
   [-109.979573, 42.969368],
   [-109.979558, 42.969261],
   [-109.979512, 42.969135],
   [-109.979497, 42.969055],
   [-109.979474, 42.968982],
   [-109.979482, 42.968887],
   [-109.979558, 42.968524],
   [-109.979817, 42.967773],
   [-109.979871, 42.967456],
   [-109.979947, 42.967269],
   [-109.980076, 42.967071],
   [-109.980191, 42.966945],
   [-109.980214, 42.966896],
   [-109.980214, 42.96683],
   [-109.980133, 42.966518],
   [-109.980073, 42.966281],
   [-109.980054, 42.966205],
   [-109.979947, 42.965839],
   [-109.979871, 42.965477],
   [-109.979764, 42.965167],
   [-109.979734, 42.965045],
   [-109.979695, 42.964916],
   [-109.979634, 42.964774],
   [-109.979497, 42.964568],
   [-109.97913, 42.964271],
   [-109.978963, 42.964069],
   [-109.978833, 42.963959],
   [-109.978673, 42.96387],
   [-109.978536, 42.96381],
   [-109.97839, 42.963787],
   [-109.977873, 42.963748],
   [-109.977871, 42.963748],
   [-109.977582, 42.963687],
   [-109.977445, 42.963615],
   [-109.977437, 42.963566],
   [-109.977452, 42.963405],
   [-109.977437, 42.96334],
   [-109.97736, 42.963276],
   [-109.977231, 42.963241],
   [-109.976972, 42.963207],
   [-109.97691, 42.963157],
   [-109.976842, 42.963085],
   [-109.976796, 42.96307],
   [-109.976674, 42.963096],
   [-109.976636, 42.963112],
   [-109.976582, 42.963119],
   [-109.976491, 42.963092],
   [-109.976415, 42.96305],
   [-109.976384, 42.963043],
   [-109.97604, 42.963035],
   [-109.975857, 42.963024],
   [-109.975636, 42.962974],
   [-109.975362, 42.962863],
   [-109.975102, 42.962783],
   [-109.974972, 42.962776],
   [-109.974865, 42.962757],
   [-109.974735, 42.962692],
   [-109.974637, 42.962597],
   [-109.974507, 42.962505],
   [-109.974423, 42.962417],
   [-109.974331, 42.962372],
   [-109.974255, 42.962356],
   [-109.974133, 42.96236],
   [-109.973981, 42.96241],
   [-109.973767, 42.962524],
   [-109.973667, 42.962536],
   [-109.973607, 42.962536],
   [-109.973508, 42.962475],
   [-109.973431, 42.962375],
   [-109.973347, 42.962173],
   [-109.973355, 42.962055],
   [-109.97337, 42.961956],
   [-109.973362, 42.96191],
   [-109.973347, 42.961872],
   [-109.973301, 42.961845],
   [-109.973288, 42.96184],
   [-109.97324, 42.961822],
   [-109.973171, 42.961811],
   [-109.973065, 42.961811],
   [-109.972973, 42.961799],
   [-109.972882, 42.96178],
   [-109.972782, 42.961708],
   [-109.972622, 42.961555],
   [-109.972432, 42.961319],
   [-109.972226, 42.961075],
   [-109.972104, 42.960945],
   [-109.971997, 42.960842],
   [-109.971951, 42.96079],
   [-109.971919, 42.960668],
   [-109.971898, 42.96059],
   [-109.971791, 42.960491],
   [-109.97163, 42.9603],
   [-109.971462, 42.960113],
   [-109.971356, 42.959979],
   [-109.97131, 42.959904],
   [-109.971287, 42.95982],
   [-109.971256, 42.959568],
   [-109.971241, 42.959503],
   [-109.971211, 42.959438],
   [-109.971165, 42.959381],
   [-109.970997, 42.959259],
   [-109.970921, 42.959213],
   [-109.970868, 42.959163],
   [-109.970806, 42.95908],
   [-109.970791, 42.959026],
   [-109.970708, 42.958839],
   [-109.970593, 42.958663],
   [-109.970432, 42.958511],
   [-109.970326, 42.958373],
   [-109.970212, 42.958198],
   [-109.970127, 42.958027],
   [-109.970036, 42.957764],
   [-109.969967, 42.957611],
   [-109.969944, 42.957477],
   [-109.969792, 42.957309],
   [-109.969677, 42.957203],
   [-109.969647, 42.957153],
   [-109.969593, 42.957099],
   [-109.96954, 42.957039],
   [-109.969502, 42.956947],
   [-109.969487, 42.956825],
   [-109.969487, 42.956646],
   [-109.969502, 42.956413],
   [-109.969501, 42.956404],
   [-109.969494, 42.956291],
   [-109.969502, 42.956196],
   [-109.969532, 42.956069],
   [-109.969532, 42.955936],
   [-109.969517, 42.955799],
   [-109.969487, 42.955666],
   [-109.969357, 42.955486],
   [-109.969166, 42.955162],
   [-109.969082, 42.954971],
   [-109.968944, 42.954697],
   [-109.96883, 42.954597],
   [-109.96867, 42.954448],
   [-109.968472, 42.954303],
   [-109.96809, 42.954178],
   [-109.967915, 42.954143],
   [-109.967785, 42.954093],
   [-109.967747, 42.954044],
   [-109.967724, 42.953994],
   [-109.967732, 42.953941],
   [-109.967731, 42.95388],
   [-109.967907, 42.95359],
   [-109.967915, 42.95351],
   [-109.967907, 42.953479],
   [-109.967793, 42.953369],
   [-109.967701, 42.95327],
   [-109.967618, 42.953079],
   [-109.967533, 42.95298],
   [-109.967327, 42.952804],
   [-109.967267, 42.952721],
   [-109.96722, 42.952644],
   [-109.967205, 42.95256],
   [-109.967213, 42.952423],
   [-109.967266, 42.952331],
   [-109.967266, 42.952182],
   [-109.967205, 42.952072],
   [-109.967137, 42.951969],
   [-109.967007, 42.951904],
   [-109.966877, 42.951858],
   [-109.966686, 42.951816],
   [-109.966465, 42.951786],
   [-109.966351, 42.951744],
   [-109.966297, 42.951687],
   [-109.966191, 42.951538],
   [-109.966106, 42.951362],
   [-109.966031, 42.951313],
   [-109.965954, 42.951256],
   [-109.965855, 42.951206],
   [-109.965786, 42.951176],
   [-109.965725, 42.951141],
   [-109.965687, 42.951053],
   [-109.965671, 42.950932],
   [-109.965671, 42.950748],
   [-109.965641, 42.950687],
   [-109.965626, 42.950573],
   [-109.965641, 42.950504],
   [-109.965733, 42.950329],
   [-109.965756, 42.950229],
   [-109.965755, 42.95018],
   [-109.96571, 42.950127],
   [-109.965634, 42.950066],
   [-109.965496, 42.950012],
   [-109.965374, 42.949978],
   [-109.965206, 42.949924],
   [-109.965031, 42.949791],
   [-109.964894, 42.94965],
   [-109.964787, 42.949493],
   [-109.964626, 42.949379],
   [-109.964497, 42.949276],
   [-109.964474, 42.949226],
   [-109.964466, 42.949192],
   [-109.964466, 42.949153],
   [-109.964496, 42.949043],
   [-109.964527, 42.948894],
   [-109.964474, 42.948776],
   [-109.96439, 42.94868],
   [-109.964291, 42.948604],
   [-109.964183, 42.948555],
   [-109.963924, 42.948486],
   [-109.963833, 42.948433],
   [-109.96365, 42.948227],
   [-109.963604, 42.948177],
   [-109.96352, 42.948127],
   [-109.963382, 42.94807],
   [-109.963307, 42.948025],
   [-109.963215, 42.947952],
   [-109.963184, 42.947876],
   [-109.963177, 42.947689],
   [-109.963184, 42.947487],
   [-109.963176, 42.947296],
   [-109.963047, 42.947098],
   [-109.962894, 42.946933],
   [-109.962686, 42.946725],
   [-109.962597, 42.946636],
   [-109.962329, 42.946361],
   [-109.962146, 42.946224],
   [-109.961987, 42.946102],
   [-109.961902, 42.946022],
   [-109.961857, 42.945972],
   [-109.961826, 42.945847],
   [-109.961773, 42.945743],
   [-109.961727, 42.945698],
   [-109.961636, 42.945648],
   [-109.961567, 42.945598],
   [-109.961475, 42.945457],
   [-109.961471, 42.945442],
   [-109.96146, 42.945396],
   [-109.961406, 42.945309],
   [-109.961162, 42.945194],
   [-109.961056, 42.945099],
   [-109.960995, 42.944958],
   [-109.960956, 42.944736],
   [-109.960957, 42.94458],
   [-109.960972, 42.944442],
   [-109.960995, 42.944366],
   [-109.96117, 42.944122],
   [-109.961277, 42.944004],
   [-109.961315, 42.943893],
   [-109.961376, 42.943744],
   [-109.961322, 42.943557],
   [-109.9612, 42.943214],
   [-109.961155, 42.943119],
   [-109.96114, 42.943046],
   [-109.961139, 42.94297],
   [-109.961223, 42.942753],
   [-109.961261, 42.942676],
   [-109.961277, 42.942604],
   [-109.961261, 42.942543],
   [-109.961224, 42.942455],
   [-109.961139, 42.942383],
   [-109.96101, 42.942314],
   [-109.960842, 42.942253],
   [-109.960613, 42.942153],
   [-109.960461, 42.942096],
   [-109.960399, 42.942054],
   [-109.960376, 42.942005],
   [-109.960376, 42.941959],
   [-109.960353, 42.941867],
   [-109.960376, 42.941784],
   [-109.960422, 42.941681],
   [-109.96043, 42.941616],
   [-109.960445, 42.941555],
   [-109.960377, 42.941402],
   [-109.960316, 42.941368],
   [-109.960216, 42.94136],
   [-109.960056, 42.941429],
   [-109.960012, 42.941454],
   [-109.959941, 42.941497],
   [-109.959805, 42.941524],
   [-109.959705, 42.941536],
   [-109.959621, 42.941536],
   [-109.959423, 42.941505],
   [-109.959096, 42.941334],
   [-109.959064, 42.941318],
   [-109.958927, 42.941238],
   [-109.958811, 42.94118],
   [-109.95898, 42.94106],
   [-109.959095, 42.940965],
   [-109.9592, 42.94088],
   [-109.9593, 42.94073],
   [-109.95933, 42.94041],
   [-109.95927, 42.94011],
   [-109.959229, 42.939988],
   [-109.95917, 42.93981],
   [-109.95917, 42.939642],
   [-109.95917, 42.939597],
   [-109.95917, 42.93958],
   [-109.959213, 42.939471],
   [-109.95923, 42.93943],
   [-109.959308, 42.939443],
   [-109.95946, 42.93947],
   [-109.959546, 42.93947],
   [-109.959626, 42.93947],
   [-109.96, 42.93947],
   [-109.96121, 42.93945],
   [-109.9632, 42.93943],
   [-109.96427, 42.93941],
   [-109.964957, 42.93941],
   [-109.9656, 42.93941],
   [-109.96795, 42.93938],
   [-109.96921, 42.939348],
   [-109.969355, 42.939185],
   [-109.9702, 42.93823],
   [-109.97018, 42.93817],
   [-109.97017, 42.93809],
   [-109.97018, 42.93792],
   [-109.97017, 42.9377],
   [-109.97018, 42.93757],
   [-109.969939, 42.937575],
   [-109.96976, 42.93758],
   [-109.96939, 42.93758],
   [-109.96922, 42.93759],
   [-109.96898, 42.93758],
   [-109.968689, 42.937531],
   [-109.968437, 42.937452],
   [-109.968037, 42.937218],
   [-109.968037, 42.93703],
   [-109.968105, 42.93671],
   [-109.968105, 42.936527],
   [-109.96806, 42.93634],
   [-109.967831, 42.935836],
   [-109.967693, 42.935467],
   [-109.967563, 42.935093],
   [-109.967541, 42.934986],
   [-109.967403, 42.934673],
   [-109.967342, 42.93441],
   [-109.967274, 42.933941],
   [-109.967281, 42.933837],
   [-109.967297, 42.933727],
   [-109.96735, 42.933639],
   [-109.967464, 42.933502],
   [-109.967541, 42.933464],
   [-109.96764, 42.933448],
   [-109.96796, 42.933426],
   [-109.96806, 42.933406],
   [-109.968135, 42.933364],
   [-109.968197, 42.933307],
   [-109.968204, 42.933235],
   [-109.968205, 42.933151],
   [-109.968167, 42.933052],
   [-109.968006, 42.932796],
   [-109.967694, 42.932434],
   [-109.967297, 42.931801],
   [-109.967182, 42.931583],
   [-109.967014, 42.931301],
   [-109.96693, 42.931102],
   [-109.96693, 42.931011],
   [-109.966953, 42.930919],
   [-109.967083, 42.930706],
   [-109.967297, 42.930423],
   [-109.967426, 42.930233],
   [-109.967655, 42.92992],
   [-109.9678, 42.929706],
   [-109.968013, 42.929477],
   [-109.968082, 42.929435],
   [-109.968197, 42.929355],
   [-109.968326, 42.929306],
   [-109.968525, 42.929271],
   [-109.968693, 42.929248],
   [-109.96902, 42.929348],
   [-109.969249, 42.929485],
   [-109.969449, 42.929618],
   [-109.96983, 42.930061],
   [-109.969937, 42.930259],
   [-109.970066, 42.930484],
   [-109.970295, 42.930793],
   [-109.970489, 42.931103],
   [-109.97063, 42.931327],
   [-109.970921, 42.931636],
   [-109.971065, 42.931782],
   [-109.971172, 42.931842],
   [-109.971203, 42.93185],
   [-109.971234, 42.931842],
   [-109.971271, 42.931827],
   [-109.971302, 42.931778],
   [-109.971309, 42.93148],
   [-109.971313, 42.931379],
   [-109.971251, 42.931378],
   [-109.971066, 42.931377],
   [-109.971005, 42.931377],
   [-109.970852, 42.931003],
   [-109.970661, 42.93061],
   [-109.970455, 42.930286],
   [-109.970097, 42.929657],
   [-109.969956, 42.929457],
   [-109.969761, 42.92918],
   [-109.969197, 42.928699],
   [-109.96867, 42.928218],
   [-109.968327, 42.928001],
   [-109.967961, 42.927822],
   [-109.967731, 42.927658],
   [-109.967296, 42.927322],
   [-109.967022, 42.927082],
   [-109.966785, 42.926918],
   [-109.966495, 42.926742],
   [-109.965946, 42.92638],
   [-109.96571, 42.926216],
   [-109.965107, 42.925941],
   [-109.964916, 42.925865],
   [-109.964786, 42.925788],
   [-109.964695, 42.92572],
   [-109.964653, 42.925664],
   [-109.964626, 42.925628],
   [-109.964596, 42.925457],
   [-109.964596, 42.925319],
   [-109.964603, 42.925201],
   [-109.964626, 42.925029],
   [-109.964672, 42.924869],
   [-109.964817, 42.924568],
   [-109.965107, 42.9239],
   [-109.965122, 42.923729],
   [-109.965107, 42.923587],
   [-109.965252, 42.923477],
   [-109.965419, 42.923397],
   [-109.965492, 42.923342],
   [-109.965496, 42.92334],
   [-109.965557, 42.923301],
   [-109.965565, 42.923252],
   [-109.965595, 42.923183],
   [-109.965595, 42.923103],
   [-109.965565, 42.922886],
   [-109.965481, 42.922771],
   [-109.965321, 42.922699],
   [-109.965153, 42.922649],
   [-109.965053, 42.922615],
   [-109.96481, 42.922479],
   [-109.964679, 42.922405],
   [-109.964549, 42.922367],
   [-109.964382, 42.922325],
   [-109.964252, 42.922188],
   [-109.964062, 42.922008],
   [-109.963962, 42.921944],
   [-109.963886, 42.921913],
   [-109.963741, 42.921894],
   [-109.963627, 42.921855],
   [-109.96355, 42.921768],
   [-109.963512, 42.921646],
   [-109.963436, 42.921501],
   [-109.963375, 42.92136],
   [-109.963344, 42.921219],
   [-109.963352, 42.921146],
   [-109.96339, 42.921062],
   [-109.963512, 42.920886],
   [-109.963627, 42.920772],
   [-109.96368, 42.920681],
   [-109.96371, 42.920532],
   [-109.963664, 42.920416],
   [-109.963611, 42.920284],
   [-109.963604, 42.920181],
   [-109.963626, 42.920105],
   [-109.963756, 42.91996],
   [-109.964161, 42.919715],
   [-109.964572, 42.919448],
   [-109.964794, 42.919311],
   [-109.96503, 42.919082],
   [-109.965176, 42.918907],
   [-109.96529, 42.918685],
   [-109.965343, 42.91851],
   [-109.965366, 42.918396],
   [-109.965335, 42.918255],
   [-109.965236, 42.918159],
   [-109.964824, 42.917896],
   [-109.964802, 42.917823],
   [-109.964786, 42.917709],
   [-109.964801, 42.917579],
   [-109.964832, 42.917442],
   [-109.96484, 42.917286],
   [-109.964824, 42.917072],
   [-109.964824, 42.916897],
   [-109.96484, 42.916835],
   [-109.964863, 42.916793],
   [-109.964924, 42.916748],
   [-109.965061, 42.916667],
   [-109.965183, 42.916561],
   [-109.965244, 42.916446],
   [-109.965282, 42.916332],

In [48]:
#IndianaDF['County'] = county
#IndianaDF['Lat'] = Lat
#IndianaDF['Long'] = Long
IndianaDF.to_csv('Indiana_OBGYNS_Final.csv')

In [49]:
IndianaDF['County'].value_counts()

Marion         188
Lake            61
Allen           60
St. Joseph      44
Warrick         30
              ...
Fulton           1
Perry            1
Huntington       1
DeKalb           1
Washington       1
Name: County, Length: 64, dtype: int64

In [4]:
#abandoned attempt to fix issues with latitude
countyCoorData = "county coordinates.csv"
countyCoor = pd.read_csv(countyCoorData)
countyCoor

,County,County Code,Code,Lat,Lng,CMS Factor,(meters),(meters).1,(meters).2,(meters).3
0,Adams,1,1,40.55,84.95,1.000034,"240,000","36,000","235,857.32","197,042.58"
1,Allen,2,2,40.90,85.05,1.000031,"240,000","36,000","244,142.67","158,173.88"
2,Bartholomew,3,3,39.00,85.85,1.000026,"240,000","36,000","310,425.25","369,491.12"
3,Benton,4,4,40.45,87.30,1.000029,"240,000","36,000","430,567.72","210,705.42"
4,Blackford,5,18-May,40.05,85.40,1.000038,"240,000","36,000","273,141.59","252,641.73"
...,...,...,...,...,...,...,...,...,...,...
87,Washington,88,31-88,37.95,86.15,1.000027,"240,000","36,000","335,281.63","486,340.68"
88,Wayne,89,68-89,39.70,85.05,1.000044,"240,000","36,000","244,142.72","291,429.82"
89,Wells,90,90,40.55,85.25,1.000034,"240,000","36,000","260,713.40","197,071.60"
90,White,91,79-91,40.20,86.90,1.000026,"240,000","36,000","397,423.61","237,652.63"
91,Whitley,92,35-92,40.65,85.50,1.000034,"240,000","36,000","281,426.85","186,057.32"